config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: %i[create index destroy]

  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['Rails.application.credentials.aws[:s3_bucket_name]']}/sitemaps/sitemap.xml.gz")

  resources :inquiries
  namespace :admin do
    resources :users
  end


  resources :questions do
    resources :answers, only: %i[new create show]
  end

  resources :answers, only: %i[edit update]
  post 'answers/:id' => 'answers#updating'

  resources :exams

  get 'genres/review/questions' => 'questions#review_index'
  resources :genres do
    resources :questions, only: %i[index new create]
  end
  resources :questions, only: %i[edit show update destroy]



  resources :password_resets, only: %i[new create edit update]
  root to: 'homes#top'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'terms', to: 'terms#index'
  get 'privacy', to: 'privacies#index'

  resources :users, only: %i[new create index show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :genre
  has_one :user, through: :genre
  has_one :answer, dependent: :destroy
  has_rich_text :statement

  validates :statement, presence: true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @genre = Genre.new
    genre = Genre.find(params[:genre_id])
    @questions = genre.questions.all.includes(:genre).order(created_at: :desc).page(params[:page]).per(6)
  end

  def review_index
    @genre = Genre.new
    @questions = current_user.questions.where(poor: true).order(created_at: :desc).page(params[:page]).per(6)
  end

  def new
    @genre = Genre.find(params[:genre_id])
    @question = Question.new
  end

  def create
    genre = Genre.find(params[:genre_id])
    @question = genre.questions.build(question_params)
    if @question.save
      flash[:success] = t('.success')
      redirect_to new_question_answer_path(@question)
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answer
  end

  def update
    @question = Question.find(params[:id])
    @question.update!(question_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy!
  end

  private

    def question_params
      params.require(:question).permit(:genre_id, :statement, :image, :poor, :exam)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1 class="qu_edit_title"><%= (t '.titile-editq') %></h1>
<div class="card border-dark mb-3 qu_edit_card" style="width: 50rem;">
  <div class="card-body qu_edit_card-body">
    <h1 class="qu_edit_card-title"><%= (t '.q') %></h1>
    <span class="qu_edit_questionform" id="qform">
      <%= form_with model: @question, local: true do |form| %>
        <p class="qu_edit_statement-title"><% form.label :statement %></p>
        <p class="qu_edit_statement-form"><%= form.rich_text_area :statement, placeholder: "本文や画像" %></p>
        <p class="qu_edit_form-btn"><%= form.submit "登録" %></p>
      <% end %>
    </span>
  </div>
</div>

app/views/questions/index.html.erb
<%= render 'shared/header' %>
<div class="qu_index_main">
  <div class="side">
    <svg style="display: none;">
      <symbol id="icon-add" viewBox="0 0 24 24">
        <path d="M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1z"></path>
      </symbol>
    </svg>
    <div class="side_head">
      <span class="qu_index_genre"><%= "ジャンル" %></span>
      <% if current_page?(genres_path) %>
        <span class="newregister">
          <button id="gbtn" class="knopf even pill shade inverse m-">
            <svg class="icon">
              <use xlink:href="#icon-add"></use>
            </svg>
          </button>
          <span class="register"><%= "新規登録" %></span>
        </span>
      <% end %>
    </div>

    <div class="accordion qu_index_accordion" id="accordionExample">
      <div class="accordion-item">
        <%= link_to "復習一覧", genres_review_questions_path, {class: "qu_index_review-index"} %>
          <% genres = current_user.genres.grouping_genres.sort_by{ |g| g[0] } %>
            <% genres.each_with_index do |(key, value), index| %>
              <h2 class="accordion-header" id="heading">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                  <%= key %>
                </button>
              </h2>
              <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <% value.sort_by{ |g| g.hiragana }.each do |v| %>
                    <span class="edit_btn" id="edit-btn" data-name='<%= v.name %>' data-id='<%= v.id %>'></span>
                  <% end %>
                </div>
              </div>
            <% end %>
      </div>
    </div>
  </div>

  <%= javascript_pack_tag 'edit_delete_vue' %>

  <div class="qu_index_memoryindex">
    <div class="row row-cols-1 row-cols-md-2 g-4">
      <% @questions.each do |question| %>
        <div class="cards" id="card" data-name="card" data-url="/questions/<%= question.id %>">
          <div class="card border-dark mb-3 h-100 qu_index_card" style="height: 30rem, width: 48rem;">
            <div class="card-body qu_index_body">
              <h2 class="card-title qu_index_card_title"><%= (t '.q') %></h2>
              <p class="card-text qu_index_card_text"><%= question.statement %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <span><%=link_to (t '.createq'), new_genre_question_path, { class: "createQ"} %></span>
  <div class="qu_index_page"><%= paginate @questions %></div>
</div>

<%= javascript_pack_tag 'questions/index' %>

app/views/questions/new.html.erb
<div class="card border-dark mb-3 qu_new_card" style="width: 50rem;">
  <div class="card-body qu_new_card-body">
    <h1 class="qu_new_card-title"><%= (t '.q') %></h1>
    <span class="qu_new_questionform" id="qform">
      <%= form_with(model: [@genre, @question], local: true) do |form| %>
          <p class="qu_new_statement-title"><% form.label :statement %></p>
          <p><%= form.rich_text_area :statement, placeholder: "本文や画像",  class: "qu_new_statement-form" %></p>
          <p><%= form.submit "登録", class: "qu_new_form-btn" %></p>
      <% end %>
    </span>
  </div>
</div>

app/views/questions/review_index.html.erb
<%= render 'shared/header' %>
<div class="main">
  <div class="side">
    <svg style="display: none;">
      <symbol id="icon-add" viewBox="0 0 24 24">
        <path d="M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1z"></path>
      </symbol>
    </svg>
    <div class="side_head">
    <span class="genre"><%= "ジャンル" %></span>

  <% if current_page?(genres_path) %>
    <span class="newregister">
      <button id="gbtn" class="knopf even pill shade inverse m-">
        <svg class="icon">
          <use xlink:href="#icon-add"></use>
        </svg>
      </button>
      <span class="register"><%= "新規登録" %></span>
    </span>
  <% end %>
  </div>

  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <%= link_to "復習一覧", genres_review_questions_path, {class: "review-index"} %>
        <% genres = current_user.genres.grouping_genres.sort_by{ |g| g[0] } %>
          <% genres.each_with_index do |(key, value), index| %>
            <h2 class="accordion-header" id="heading">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                <%= key %>
              </button>
            </h2>
            <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% value.sort_by{ |g| g.hiragana }.each do |v| %>
                  <span class="edit_btn" id="edit-btn" data-name='<%= v.name %>' data-id='<%= v.id %>'></span>
                <% end %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <%= javascript_pack_tag 'edit_delete_vue' %>

  <div class="rev_index_memoryindex">
    <div class="row row-cols-1 row-cols-md-2 g-4">
      <% @questions.each_with_index do |question, index| %>
        <div class="qacards" id="card" data-name="card" data-url="/questions/<%= question.id %>">
          <div class="card border-dark mb-3 h-100 rev_index_card" style="height: 30rem, width: 48rem;">
            <div class="card-body rev_index_card-body">
              <h2 class="rev_index_card-title"><%= "Q." %></h2>
              <p class="rev_index_card-text"><%= question.statement %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="rev_index_page"><%= paginate @questions %></div>
</div>

<%= javascript_pack_tag 'questions/review_index' %>

app/views/questions/show.html.erb
<div class="qu_show_guidance">
  <span>カードをクリックしたら、答えが見えるよ!</span>
  <div class="qu_show_question-card" id="qacard">
    <div class="card border-dark mb-3" style="width: 40rem;">
        <h1 class="qu_show_qcard-title"><%= (t '.q') %></h1>
      <div class="qu_show_qcard-body">
        <h1 class="qcard-content"><%= @question.statement %></h1>
      </div>
      <h1 class="qu_show_acard-title"><%= (t '.a') %></h1>
      <div class="qu_show_acard-body" id="abody">
        <span class="qu_show_answer"><%= @answer.solution %></span>
        <span><%= (t '.process') %></span>
        <span class="qu_show_acard-content"><%= @answer.process %></span>
      </div>
    </div>
  </div>
</div>

<div class="qu_show_review">
  <%= form_with model: @question, local: true do |form| %>
    <%= form.label :poor, class: 'qu_show_checkbox-label' %>
    <%= form.check_box :poor ,{ style: 'transform: scale(2.5);', class: 'qu_show_check-box' }, "true", "false" %>
    <%= form.submit "登録", class: 'qu_show_checkbox-btn' %>
  <% end %>
</div>

<div><%=link_to (t '.editq'), edit_question_path, class: 'qu_show_question-edit' %></div>
<div><%=link_to (t '.edita'), edit_answer_path, class: 'qu_show_answer-edit' %></div>
<span class="qu_show_qdelete">
  <%= link_to question_path(@question), method: :delete, data: { confirm: "ご覧の問題を削除しますが、よろしいですか？"} do %>
    <i id="trash" class="fas fa-trash"></i>
  <% end %>
</span>

<%= javascript_pack_tag 'questions/show' %>