config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: %i[create index destroy]

  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['Rails.application.credentials.aws[:s3_bucket_name]']}/sitemaps/sitemap.xml.gz")

  resources :inquiries
  namespace :admin do
    resources :users
  end


  resources :questions do
    resources :answers, only: %i[new create show]
  end

  resources :answers, only: %i[edit update]
  post 'answers/:id' => 'answers#updating'

  resources :exams

  get 'genres/review/questions' => 'questions#review_index'
  resources :genres do
    resources :questions, only: %i[index new create]
  end
  resources :questions, only: %i[edit show update destroy]



  resources :password_resets, only: %i[new create edit update]
  root to: 'homes#top'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'terms', to: 'terms#index'
  get 'privacy', to: 'privacies#index'

  resources :users, only: %i[new create index show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :inquiry
  belongs_to :end_user, class_name: 'User', foreign_key: 'end_user_id', optional: true
  belongs_to :admin_user, class_name: 'User', foreign_key: 'admin_user_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(15)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def create
    @notification = Notification.find(params[:id])
    @notification.update
    redirect_to admin_users_path
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy!
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% end_user = notification.end_user %>
<% admin_user = notification.admin_user %>
  <ul class="list-group">
    <li class="list-group-item">
      <% case notification.action %>
        <% when 'information' then %>
          <span class="delete-btn">
            <%= link_to notification_path(notification.id), method: :delete, data: { confirm: "削除しますが、よろしいですか？"} do %>
              <i id="trash" class="fas fa-trash"></i>
            <% end %>
          </span>
          <span>【<%= current_user.name %><%= notification.inquiry.email %>より】お問い合わせが届きました</span>
        <span><%= notification.inquiry.message %></span>
      <% end %>
    </li>
  </ul>

app/views/notifications/index.html.erb
<h1 class="notifi_title">通知一覧</h1>
<div class="notifi_common-contents">
  <div class="notifi_informations">
    <% if @notifications.exists? %>
      <ul class="notifi_allnotifications-list">
        <%= render @notifications %>
      </ul>
    <% else %>
      <p class="notifi_allnotifications-no">通知はありません</p>
    <% end %>
  </div>
</div>
<div class="notif_index_page"><%= paginate @notifications %></div>