config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: %i[create index destroy]

  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['Rails.application.credentials.aws[:s3_bucket_name]']}/sitemaps/sitemap.xml.gz")

  resources :inquiries
  namespace :admin do
    resources :users
  end


  resources :questions do
    resources :answers, only: %i[new create show]
  end

  resources :answers, only: %i[edit update]
  post 'answers/:id' => 'answers#updating'

  resources :exams

  get 'genres/review/questions' => 'questions#review_index'
  resources :genres do
    resources :questions, only: %i[index new create]
  end
  resources :questions, only: %i[edit show update destroy]



  resources :password_resets, only: %i[new create edit update]
  root to: 'homes#top'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'terms', to: 'terms#index'
  get 'privacy', to: 'privacies#index'

  resources :users, only: %i[new create index show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_rich_text :answer
  belongs_to :question

  validates :solution, presence: true
  validates :process, presence: true

  validate :exam_valid?

  private

    def exam_valid?
      if exam != nil && exam <= Time.zone.today
        errors.add(:exam, 'は今日以降の日付で設定してください。')
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  require 'mechanize'
  require "nkf"

  belongs_to :user
  has_many :questions, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :user_id }, format: { without: /\A(?=.*[一-龠々])(?=.*[ぁ-んァ-ヴa-zA-Z0-9])/ }

  attr_accessor :hiragana

  AGENT = Mechanize.new
  BASE_URL = 'https://yomikatawa.com/kanji/'

  def self.grouping_genres
    Genre.all.group_by do |genre|
      name = genre.name
      if genre.name.match?(/[一-龠々]/)
        name = AGENT.get(BASE_URL + genre.name).search('#content p').first.inner_text
        genre.hiragana = name
      elsif genre.name.match?(/[ァ-ヴ]/)
        genre.hiragana  = NKF.nkf("-h1 -w", name)
      else
        genre.hiragana = name
      end

      case name[0]
      when /[ぁ-お]/
        'あ'
      when /[か-ご]/
        'か'
      when /[さ-ぞ]/
        'さ'
      when /[た-ど]/
        'た'
      when /[な-の]/
        'な'
      when /[は-ぽ]/
        'は'
      when /[ま-も]/
        'ま'
      when /[ゃ-よ]/
        'や'
      when /[ら-ろ]/
        'ら'
      when /[ゎ-を]/
        'わ'
      when /[ァ-オ]/
        'あ'
      when /[カ-ゴ]/
        'か'
      when /[サ-ゾ]/
        'さ'
      when /[タ-ド]/
        'た'
      when /[ナ-ノ]/
        'な'
      when /[ハ-ポ]/
        'は'
      when /[マ-モ]/
        'ま'
      when /[ャ-ヨ]/
        'や'
      when /[ラ-ロ]/
        'ら'
      when /[ヮ-ヲ]/
        'わ'
      when /[aA]/
        'A'
      when /[bB]/
        'B'
      when /[cC]/
        'C'
      when /[dD]/
        'D'
      when /[eE]/
        'E'
      when /[fF]/
        'F'
      when /[gG]/
        'G'
      when /[hH]/
        'H'
      when /[iI]/
        'I'
      when /[jJ]/
        'J'
      when /[kK]/
        'K'
      when /[lL]/
        'L'
      when /[mM]/
        'M'
      when /[nN]/
        'N'
      when /[oO]/
        'O'
      when /[pP]/
        'P'
      when /[qQ]/
        'Q'
      when /[rR]/
        'R'
      when /[sS]/
        'S'
      when /[tT]/
        'T'
      when /[uU]/
        'U'
      when /[vV]/
        'V'
      when /[wW]/
        'W'
      when /[xX]/
        'X'
      when /[yY]/
        'Y'
      when /[zZ]/
        'Z'
      else
        name[0]
      end
    end
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  has_one :notification, dependent: :destroy

  validates :email, presence: true
  validates :message, presence: true

  def create_notification_inquiry!(current_user)
    admin = User.find_by(admin: true)
    save_notification_inquiry!(current_user, admin.id)
  end

  def save_notification_inquiry!(current_user, admin_user_id)
    notification = current_user.active_notifications.new(
        admin_user_id: admin_user_id,
        inquiry_id: id,
        action: 'information'
      )
      notification.save if notification.valid?
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :inquiry
  belongs_to :end_user, class_name: 'User', foreign_key: 'end_user_id', optional: true
  belongs_to :admin_user, class_name: 'User', foreign_key: 'admin_user_id', optional: true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :genre
  has_one :user, through: :genre
  has_one :answer, dependent: :destroy
  has_rich_text :statement

  validates :statement, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :genres, dependent: :destroy
  has_many :questions, through: :genres
  has_many :inquiries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'end_user_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'admin_user_id', dependent: :destroy

  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :to_genres, only: [:index], if: :after_current_user_status


  def index
    @answers = Answer.joins({:question => :genre}).where(genres:{ user_id: current_user.id }, exam: Time.current.to_date).order(created_at: :desc).page(params[:page]).per(8)
  end

  private

    def after_current_user_status
      current_user.status == true
    end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit; end

  # /users/new
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new #/users
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :remember_me)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'My Nort',
      title: 'My Nort',
      reverse: true,
      charset: 'utf-8',
      description: '学校のテスト本番で暗記したことが思い出せない・暗記が苦手、そんな方におすすめなのが「My Nort」です。',
      keywords: '勉強,暗記,苦手',
      canonical: request.original_url,
      separator: '|', # これで"タイトル | サイトネーム"ってなる
      icon: [
        { href: image_url('https://img14.shop-pro.jp/PA01308/843/etc/%A5%DE%A5%A4%A5%CE%A1%BC%A5%C89.JPG?cmsp_timestamp=20200721144234') },
        { href: image_url('https://img14.shop-pro.jp/PA01308/843/etc/%A5%DE%A5%A4%A5%CE%A1%BC%A5%C89.JPG?cmsp_timestamp=20200721144234'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        local: 'ja-JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@MyMemorial02'
      }
    }
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>
</figure>

app/views/shared/_answer_validates_error_messages.html.erb
<% if @answer.errors.any? %>
  <div id="error_message" class="alert alert-danger">
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_message" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header class="headerbar">
  <span class="header_app_title"><%= "My Nort" %></span>
    <ul class="nav">
      <% if current_user.admin == true %>
        <li class="nav-item">
          <span class="admin"><%= link_to admin_users_path do %>
            <i class="fas fa-envelope icon"></i>
            <span class="admin_tag"><%= "管理者" %></span>
          <% end %>
          </span>
        </li>
      <% else %>
        <li class="nav-item">
          <span class="admin"><%= link_to new_inquiry_path do %>
            <i class="fas fa-paper-plane icon"></i>
            <span class="admin_tag"><%= "問い合わせ" %></span>
          <% end %>
          </span>
        </li>
      <% end %>
        <li class="nav-item">
          <span class="logoutlink"><%= link_to logout_path, method: :delete do %>
            <i class="fas fa-running icon"></i>
            <span class="logout"><%= "ログアウト" %></span>
          <% end %>
          </span>
        </li>
        <li class="nav-item">
          <span class="mypage"><%= link_to user_path(current_user) do %>
            <i class="fas fa-user icon"></i>
            <span class="userinfo"><%= "ユーザー情報" %></span>
          <% end %></span>
        </li>
        <li class="nav-item">
          <span class="image"><%= link_to genres_path do %>
            <%= image_tag 'nort.png', class: 'rounded-circle mr15 head_image'%>
            <span class="image_genre"><%= "ジャンルページへ" %></span>
          <% end %></span>
        </li>
    </ul>
</header>

app/views/shared/_inquiry_validates_error_messages.html.erb
<% if @inquiry.errors.any? %>
  <div id="error_message" class="alert alert-danger">
    <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="side">

  <svg style="display: none;">
    <symbol id="icon-add" viewBox="0 0 24 24">
      <path d="M18 13h-5v5c0 .55-.45 1-1 1s-1-.45-1-1v-5H6c-.55 0-1-.45-1-1s.45-1 1-1h5V6c0-.55.45-1 1-1s1 .45 1 1v5h5c.55 0 1 .45 1 1s-.45 1-1 1z"></path>
    </symbol>
  </svg>
  <div class="side_head">
  <span class="genre"><%= "ジャンル" %></span>

  <% if current_page?(genres_path) %>
    <span class="newregister">
      <button id="gbtn" class="knopf even pill shade inverse m-">
        <svg class="icon">
          <use xlink:href="#icon-add"></use>
        </svg>
      </button>
      <span class="register"><%= "新規登録" %></span>
    </span>
  <% end %>
  </div>

  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <%= link_to "復習一覧", genres_review_questions_path, {class: "review-index"} %>
        <% genres = current_user.genres.grouping_genres.sort_by{ |g| g[0] } %>
          <% genres.each_with_index do |(key, value), index| %>
            <h2 class="accordion-header" id="heading">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                <%= key %>
              </button>
            </h2>
            <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <% value.sort_by{ |g| g.hiragana }.each do |v| %>
                  <span class="edit_btn" id="edit-btn" data-name='<%= v.name %>' data-id='<%= v.id %>'></span>
                <% end %>
              </div>
            </div>
          <% end %>
    </div>
  </div>

  <span class="genreform" id="gform">
    <%= form_with model: genre, local: true do |form| %>
      <%= form.text_field :name, class: 'gname' %>
      <%= form.submit "登録", class: 'gn_btn' %>
    <% end %>
  </span>
</div>

<%= javascript_pack_tag 'edit_delete_vue' %>

<%= javascript_pack_tag 'sidebar' %>

app/views/shared/_testform.html.erb
<%= form_with(model: [@question], local: true) do |form| %>
  <%= form.number_field :test, class: "test-form", min: 1, max: 31 %>
  <%= form.submit "登録" %>
<% end %>

app/views/shared/_validates_error_messages.html.erb
<% if @answer.errors.any? %>
  <div id="error_message" class="alert alert-danger">
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>