config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: %i[create index destroy]

  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['Rails.application.credentials.aws[:s3_bucket_name]']}/sitemaps/sitemap.xml.gz")

  resources :inquiries
  namespace :admin do
    resources :users
  end


  resources :questions do
    resources :answers, only: %i[new create show]
  end

  resources :answers, only: %i[edit update]
  post 'answers/:id' => 'answers#updating'

  resources :exams

  get 'genres/review/questions' => 'questions#review_index'
  resources :genres do
    resources :questions, only: %i[index new create]
  end
  resources :questions, only: %i[edit show update destroy]



  resources :password_resets, only: %i[new create edit update]
  root to: 'homes#top'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'terms', to: 'terms#index'
  get 'privacy', to: 'privacies#index'

  resources :users, only: %i[new create index show]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :to_genres, only: [:index], if: :after_current_user_status


  def index
    @answers = Answer.joins({:question => :genre}).where(genres:{ user_id: current_user.id }, exam: Time.current.to_date).order(created_at: :desc).page(params[:page]).per(8)
  end

  private

    def after_current_user_status
      current_user.status == true
    end


end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/index.html.erb
<h2 class="test_title">今日のテスト分</h2>
<div class="ex_index_memoryindex">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @answers.each do |answer| %>
      <div class="cards" id="card" data-name="card" data-url="/questions/<%= answer.question.id %>">
        <div class="card border-dark mb-3 h-100 ex_index_card" style="height: 30rem, width: 48rem;">
          <div class="card-body ex_index_card">
            <h2 class="card-title"><%= (t '.q') %></h2>
            <p class="card-text"><%= answer.question.statement %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<span><%=link_to 'テストを終了する', genres_path(status: false), { class: "to_genre" } %></span>
<div class="ex_index_page"><%= paginate @answers %></div>

<%= javascript_pack_tag 'exams/index' %>

app/views/exams/show.html.erb
<div class="ex_show_question-card" id="qacard">
  <div class="card border-dark mb-3" style="width: 40rem;">
      <h1 class="ex_show_qcard-title"><%= (t '.q') %></h1>
    <div class="ex_show_qcard-body">
      <h1 class="qcard-content"><%= @question.statement %></h1>
    </div>
      <h1 class="ex_show_acard-title"><%= (t '.a') %></h1>
    <div class="ex_show_acard-body" id="abody">
      <span class="ex_show_answer"><%= @answer.solution %></span>
      <span><%= (t '.process') %></span>
      <span class="ex_show_acard-content"><%= @answer.process %></span>
    </div>
  </div>
</div>

<%= @answer.exam %>

<div class="ex_show_review">
  <%= form_with model: @question, local: true do |form| %>
    <%= form.label :poor, class: 'ex_show_checkbox-label' %>
    <%= form.check_box :poor ,{ style: 'transform: scale(2.5);', class: 'check-box' }, "true", "false" %>
    <%= form.submit "登録", class: 'ex_show_checkbox-btn' %>
  <% end %>
</div>

<div><%=link_to (t '.editq'), edit_question_path, class: 'ex_show_question-edit' %></div>
<div><%=link_to (t '.edita'), edit_answer_path, class: 'ex_show_answer-edit' %></div>
<span class="ex_show_qdelete">
  <%= link_to question_path(@question), method: :delete, data: { confirm: "ご覧の問題を削除しますが、よろしいですか？"} do %>
    <i id="trash" class="fas fa-trash"></i>
  <% end %>
</span>

<%= javascript_pack_tag 'exams/show' %>